### PR TITLE
Add notice about game settings while using LatencyFlex, minor typo correction

### PR DESCRIPTION
**Pull request by KyleGospo**

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Does adaptive supersampling cause issues with LFX? I kinda hoped that it would work but I also see how it could mess up the measurements.

**Comment by ishitatsuyuki** [comment]
Also, I don't recommend using external frame limiters as they don't play well with LFX's measurements (it doesn't seem to be a serious problem in practice, but still it's not good in theory). If possible, use the in-game frame limiter instead. The Source engine should have a pretty good one.

**Comment by abarichello** [comment]
Yeah, should probably update that section to use `fps_max` command instead

**Comment by KyleGospo** [comment]
Thanks for the info @ishitatsuyuki, I had no idea about that limitation.

I've changed the guide to use +fps_max_use_refresh 1 since that solves the stated issue (tearing).
As for the super sampling, it should work fine, but if you set the desired framerate too low it'll drive up your GPU usage to 100% and not behave well alongside LFX.

**Comment by abarichello** [comment]
Thanks! 🐧

**Pull request merged**
