### PR TITLE
Add chathooks cla and some useful commands

### PR DESCRIPTION
**Pull request by emma-miler**

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
`-profile=` and `-enablechathooks` are both `v1.5.0`, right? Cause then that change should be merged into [`next-release`](https://github.com/R2Northstar/NorthstarWiki/tree/next-release).

**Comment by GeckoEidechse** [comment]
Actually, `-profile=` is already in there: bfea865a2f71767ddec239dd1072b3e58dc29efd

**Comment by emma-miler** [comment]
oh right. I added it cause I didn't see it in there, but I forgot that it wasnt on main yet. Should be fixed when merging right?

**Comment by GeckoEidechse** [comment]
Tbh, probably best to just close this and make separate PRs for flag and table fix. One going to `main`, the other to `next-release`.

**Comment by emma-miler** [comment]
Not sure why they'd have to be separate? Both flags will be newly added in 1.5.0

**Comment by GeckoEidechse** [comment]
Point being that until `v1.5.0` is out, stuff related to it should be in `next-release`. I know it should release soon™ but I'd rather not merge pre-release stuff before it's actually out ¯\\\_(ツ)\_/¯

**Comment by emma-miler** [comment]
ohhh, alright. I can just re-open the PR to merge with `next-release` in that case.

**Pull request closed without merging**
