### PR TITLE
Add instructions for running mdbook linkcheck

### PR DESCRIPTION
**Pull request by GeckoEidechse**
Allows checking if all relative links inside the mdBook are valid. Especially useful for ensuring updated links when moving content around.

### CODE REVIEW

**Comment by itscynxx** [comment]
Works and warns of links, I would suggest adding a section similar to:

## mdBook-linkcheck
There's a community made package that you can use alongside mdBook to show you some potentially invalid hyperlinks in markdown files called [mdBook-linkcheck](https://github.com/Michael-F-Bryan/mdbook-linkcheck)

Although not required, you may find it helpful to use alongside mdBook to ensure you've linked things properly

To install mdBook-linkcheck use the following link if:
- [you have Rust toolchain installed](https://github.com/Michael-F-Bryan/mdbook-linkcheck#getting-started)
- [you DON'T have Rust toolchain installed](https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/latest) (add `mdBook-linkcheck.exe` to the same folder `mdBook.exe` is located)

**Comment by GeckoEidechse** [comment]
Failing link is
```
https://help.ea.com/en/help/pc/link-ea-and-steam/
```
wtf?

https://github.com/R2Northstar/NorthstarWiki/actions/runs/6484396432/job/17608135877?pr=238#step:4:420


Need figure out if there's a way to ignore external links...

**Comment by itscynxx** [comment]
> Need figure out if there's a way to ignore external links...

does adding `follow-web-links = false` under `output.linkcheck` change anything

**Comment by GeckoEidechse** [comment]
> > Need figure out if there's a way to ignore external links...
> 
> does adding `follow-web-links = false` under `output.linkcheck` change anything

Was about to try that until I realised that `ocular-d/md-linkcheck-action@master` uses https://github.com/tcort/markdown-link-check and not https://github.com/Michael-F-Bryan/mdbook-linkcheck (i.e. a completely different tool xD)

It seems there's no pre-made Action for mdBook-linkcheck :c

**Comment by GeckoEidechse** [comment]
I'm gonna skip CI for this PR and make a separate one instead ^^

**Comment by GeckoEidechse** [comment]
Gonna merge this as is for now and then focus on CI in a second PR

**Pull request merged**
