### PR TITLE
Make FAQ section use references

### PR DESCRIPTION
**Pull request by itscynxx**
makes sections referencing faq work on both github and gitbook instead of just on gitbook, not entirely required but figured itd be nice and make it more straightforward to those writing in the future, hopefully

### CODE REVIEW

**Review by GeckoEidechse — COMMENTED** [review]
Did you check if it actually works on GitBook or are you just basing it on how other headers are formatted?
(Which is fine, just checking whether it was tested or not ^^)

**Comment by itscynxx** [comment]
out of curiosity, what do you mean checked on gitbook? Currently the way to link to faq is to just link to the entire question, which while it does work, leads to some weird interactions when trying to create a link to it (hence why last time i had to open a pr right after to fix it)

basically, github makes it so a `/` in text translates to a `-` in the url, while gitbook simply removes the space there and combines the words (e.g. `EA/origin` becomes `EA-origin` on github, but `EAorigin` on gitbook) and the way it works currently makes it only work on gitbook, but these updates are formatted the same way as the other links to parts of the wiki i've used, just updated for the faq, and as far as i know ive updated all links to the faq (i checked through each page of the wiki and changed all i found)

**Comment by GeckoEidechse** [comment]
> out of curiosity, what do you mean checked on gitbook?

You can setup a project on GitBook via their free tier and link it to a GitHub repo. Then you see the changes from the GitHub repo in your own GitBook instance.

As I said, not necessary, was just wondering if you did that ^^

**Review by GeckoEidechse — APPROVED** [review]
Looks fine as far as I can tell. Let's hope the links actually work @CooldudePUGS maybe double check after it's merged ^^

**Pull request merged**
