### PR TITLE
Update launch-arguments.md

### PR DESCRIPTION
**Pull request by emma-miler**

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
This is for a feature that releases with `v1.5.0`, right?

**Comment by emma-miler** [comment]
> This is for a feature that releases with `v1.5.0`, right?

yup

**Comment by GeckoEidechse** [comment]
In that case I'll wait with the merge until `v.1.5.0` is out to avoid having information conflicting with current release. We'll probably add a branch for pre-release documentation some time in the future ^^

**Comment by abarichello** [comment]
Added a `next-release` branch, from now on specific docs to newly added features will stay there until a new Northstar version is released, when that happens we'll rebase it onto master.

**Pull request merged**
