### PR TITLE
Change prerequisites to "getting started" 

### PR DESCRIPTION
**Pull request by NoCatt**
I hope this makes users click on that section first and not just skip to the modding / server hosting chat

### CODE REVIEW

**Review by GeckoEidechse — CHANGES_REQUESTED** [review]
Overall I like the change.

Just make sure to update all the links ;)

https://github.com/NoCatt/NorthstarWiki/blob/f8b48b58fa7d86ba71efd14c4261c4f0365740c6/docs/hosting-a-server-with-northstar/troubleshooting.md?plain=1#L45

**Comment by NoCatt** [comment]
> Overall I like the change.
> 
> Just make sure to update all the links ;)
> 
> https://github.com/NoCatt/NorthstarWiki/blob/f8b48b58fa7d86ba71efd14c4261c4f0365740c6/docs/hosting-a-server-with-northstar/troubleshooting.md?plain=1#L45

it's resolved, next time make a PROPER change request not this weird link to a line thing ( then I can actually press resolve )

**Comment by GeckoEidechse** [comment]
> it's resolved, next time make a PROPER change request not this weird link to a line thing ( then I can actually press resolve )

GitHub won't let me make an edit suggestion on lines that weren't changed. Complain to GitHub ig :P

**Review by GeckoEidechse — APPROVED** [review]
Change looks good and should hopefully be more self-explanatory to novices \^\^

I also double-checked to make sure all occurrences of linking to prerequisites have been updated.

**Pull request merged**
